Validate the username when creating users through the api
SpongePowered/SpongeAuth pull request #292
Opened 2019-01-26 11:56 UTC by felixoi

2019-01-26 12:12 UTC, felixoi commented
I have no clue why the test fail.

2019-01-27 01:05 UTC, lukegb commented
That's not your fault, the requirements.txt is actually broken. I'll fix the tests first, and then ask you to rebase.

2019-01-27 15:00 UTC, felixoi commented
Good. Added a test and travis is passing now.

2019-01-27 15:05 UTC, lukegb requested changes
Thanks for the contribution! Two small things, otherwise you're good to go.

2019-01-27 15:05 UTC, lukegb commented on spongeauth/api/views.py
> +        accounts.models.validate_username(username)
I'd rather you run all model validation here: basically, before `.save` is called, you should call `.full_clean()`, which will do all the validation (including username validation):

https://docs.djangoproject.com/en/2.1/ref/models/instances/#django.db.models.Model.full_clean

Your test shouldn't need to change.

2019-01-27 15:05 UTC, lukegb commented on spongeauth/api/views.py
> +        return django.http.JsonResponse({'errors': exc.messages}, status=422)
Instead of 422, please use `httplib.UNPROCESSABLE_ENTITY`

(you'll need to `import httplib` too)

2019-01-27 15:14 UTC, lukegb commented on spongeauth/api/views.py
> +        return django.http.JsonResponse({'errors': exc.messages}, status=422)
Whoops, sorry, it's `import http` in Python 3, and `http.HTTPStatus.UNPROCESSABLE_ENTITY`

2019-01-27 15:53 UTC, lukegb approved these changes

2019-01-27 15:53 UTC, merged