Add discord id to user profile
SpongePowered/SpongeAuth pull request #294
Opened 2019-02-01 15:18 UTC by felixoi

2019-02-02 17:49 UTC, felixoi commented
Did I broke all the tests?

2019-03-02 20:54 UTC, lukegb commented
Whoops, sorry I haven't reviewed this yet.

2019-03-02 20:56 UTC, lukegb requested changes
I'll go merge all the pending pyup PRs, then can you rebase?

2019-03-02 20:56 UTC, lukegb commented on spongeauth/accounts/models.py
> +    if not re.match(r'^(.*)#(\d{4})$', discord_id):
This should probably be at least .+, because we shouldn't permit `#1234` as a Discord ID. Probably?

2019-03-02 20:56 UTC, lukegb commented on spongeauth/accounts/tests/test_discord_id_validation.py
> +]
So yeah, add a test here to prohibit #1234 ;)

2019-03-02 22:01 UTC, lukegb approved these changes

2019-03-02 22:03 UTC, merged