Add REQUIRE_EMAIL_CONFIRM setting
SpongePowered/SpongeAuth pull request #7
Opened 2017-01-16 19:50 UTC by windy1

Signed-off-by: Walker Crouse <walkercrouse@hotmail.com>

2017-01-16 22:14 UTC, lukegb requested changes
Can you also add a test to

https://github.com/lukegb/SpongeAuth/blob/0295e712ee0a650b86242d9d9a681912c9c72580/spongeauth/accounts/tests/test_middleware_enforce_verified_emails.py

in `TestMustVerify` to make sure that it returns `False` if `REQUIRE_EMAIL_CONFIRM` is `False`, even if the other conditions are met?

2017-01-16 22:14 UTC, lukegb commented on spongeauth/accounts/middleware.py
> +                resolve(url).func, 'allow_without_verified_email', False) or not settings.REQUIRE_EMAIL_CONFIRM
I don't think you need this here as well.

2017-01-16 22:14 UTC, lukegb commented on spongeauth/spongeauth/settings/prod.py
> +REQUIRE_EMAIL_CONFIRM = True
If this is true in base it's probably not worthwhile setting it to `True` here.

2017-01-17 18:56 UTC, windy1 commented
@lukegb Updated

2017-01-18 19:34 UTC, lukegb approved these changes

2017-01-18 19:34 UTC, lukegb commented
Thanks!

2017-01-18 19:34 UTC, merged